### ISSUE TITLE
Update docs for LESS

### ISSUE THREAD

**Issue by LucaColonnello** [danlevan/google-material-color#7]
Hi,
in the README file there's an error.

```
@import 'palette';
...

.my-div {
  .palette('Light Blue', '700');
  background-color: @palette;

  .palette('Red'); // default shade is 500
  color: @palette;
}
```

In LESS you can't do this.
The `@palette` variable will be orverwritten by the second mixin call.
So, @palette is equal to Red color both for background-color and color assignments.

**Comment by danlevan** [comment]
Oh you're right :+1: 

Actually, the `@palette` remained to blue for both. I'm not really sure how less handles that. Anyways, I changed the doc to:

```less
@import 'palette';
...

.issue-7 {
  .palette('Light Blue', '700');
  background-color: @palette;

  // get @palette in its own scope otherwise @palette will be overwritten
  &{
    .palette('Red'); // default shade is 500
    color: @palette;
  }
}

```

Thanks for the issue, never would have noticed :)
